### ISSUE TITLE
Teams Web Logs collection fails when logs are generated within a folder

### ISSUE THREAD

**Issue by mibrest-MSFT** [microsoft/TeamsDataCollector#1]
When Teams Web Logs are generated in a folder in the Downloads folder, the script fails to copy the individual log files (and thus does not copy them at all).

Adding a "-Recurse" at line 779 fixes the issue:
`$FileResult = (Get-ChildItem $FolderPath -Recurse | Where-Object { $_.Name -match "MSTeams Diagnostics"  -and $_.LastWriteTime -gt (get-date).AddMinutes(-2)})`

**Comment by chtartMSFT** [comment]
Thanks, yes they added more structure to the output folders which was not handled.
I've just pushed a new version which should resolve this.

**Comment by chtartMSFT** [comment]
Resolved with version 1.0.2104.1501
